apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: flex
  name: flex-slack-metrikker{{#if RUN_ON_DEPLOY}}-run-on-deploy{{/if}}
  namespace: flex
spec:
  image: {{image}}
  {{#unless RUN_ON_DEPLOY}}
  schedule: "0 0 * * *"
  {{/unless}}
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  envFrom:
    - secret: team-flex-slack-bot-slack-token
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: {{gcpProjectId}}
        role: roles/bigquery.readSessionUser
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: {{gcpProjectId}}
        role: roles/bigquery.dataViewer
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: {{gcpProjectId}}
        role: roles/bigquery.jobUser
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: 3.68.175.98
        - host: 3.68.170.153
        - host: 3.68.124.168
        - host: 3.68.124.95
        - host: 18.159.197.225
        - host: 52.29.238.212
