name: workflow
on: push

permissions:
  contents: "read"
  checks: "write"
  id-token: "write"

jobs:
  build-and-push:
    name: Build and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Lint
        run: ./gradlew ktlintCheck

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew shadowjar -x test

      - name: docker-build-push
        if: github.ref_name == 'main'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: flex
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  nais-oneoff-deploy:
    if: github.ref_name == 'main'
    needs: [build-and-push]
    uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@main
    with:
      image: ${{ needs.build-and-push.outputs.image }}
      prod-only: "true"
      prod-vars: nais/prod.yaml
      nais-template: nais/naisjob.yaml
      extra-vars: RUN_ON_DEPLOY=true
    secrets: inherit